// Re-export all Rust-generated bindings.
// This file is the stable public surface of @booksforge/shared-types.
//
// The bindings/ directory is regenerated by:
//   cargo test -p booksforge-ipc
// Never hand-edit files under bindings/.

export type { AppVersion } from "./bindings/AppVersion";
export type { BooksForgeError } from "./bindings/BooksForgeError";
export type { NodeInfo } from "./bindings/NodeInfo";
export type { NodeCreateInput } from "./bindings/NodeCreateInput";
export type { NodeUpdateInput } from "./bindings/NodeUpdateInput";
export type { SceneSaveInput } from "./bindings/SceneSaveInput";
export type { SceneLoadResult } from "./bindings/SceneLoadResult";
export type { RecoveryStatus } from "./bindings/RecoveryStatus";
export type { CreateProjectInput } from "./bindings/CreateProjectInput";
export type { OpenProjectInput } from "./bindings/OpenProjectInput";
export type { OpenProjectResult } from "./bindings/OpenProjectResult";
export type { RecentProjectEntry } from "./bindings/RecentProjectEntry";

// Non-generated types used by Tauri command responses.
export interface OllamaStatusResponse {
  running: boolean;
  version: string | null;
}
