// Re-export all Rust-generated bindings.
// This file is the stable public surface of @booksforge/shared-types.
//
// The bindings/ directory is regenerated by:
//   cargo test -p booksforge-ipc
// Never hand-edit files under bindings/.

export type { AppVersion } from "./bindings/AppVersion";
export type { BooksForgeError } from "./bindings/BooksForgeError";
export type { CreateProjectInput } from "./bindings/CreateProjectInput";
export type { OpenProjectInput } from "./bindings/OpenProjectInput";
export type { OpenProjectResult } from "./bindings/OpenProjectResult";
export type { RecentProjectEntry } from "./bindings/RecentProjectEntry";

// Non-generated types used by Tauri command responses.
export interface OllamaStatusResponse {
  running: boolean;
  version: string | null;
}
