// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type BookKind = "literary-fiction" | "genre-fiction" | "non-fiction" | "memoir" | "childrens-book";
