// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { BookKind } from "./BookKind";

/**
 * One genre pack — system prompt, lens, critic axes, polish stack
 * ordering, rubric weights, hard rules.
 */
export type GenrePack = { kind: BookKind, 
/**
 * Genre-label string the agent prompt templates branch on
 * (`"literary_fiction" | "genre_fiction" | "non_fiction"`).
 */
genre_label: string, system_prompt: string, draft_lens: string, critic_axes: Array<string>, polish_stack_order: Array<string>, rubric_weights: { [key in string]?: number }, hard_rules: Array<string>, };
