// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Event payload emitted on `agent-run-started`.
 */
export type AgentRunStartedEvent = { 
/**
 * UUID-ish id the frontend uses to match start ↔ complete and to
 * pass to `agent_cancel`.  Distinct from the orchestrator's
 * internal `task_id` because we issue this *before* the task row
 * is created (so we can cancel even during setup).
 */
run_id: string, agent_id: string, 
/**
 * ISO-8601 timestamp when the dispatch started.
 */
started_at: string, };
