// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Result of `ai_suggest` — returned synchronously while the stream runs
 * in a background task.
 */
export type AiSuggestStartedResult = { 
/**
 * Opaque id used for `ai_cancel` and as the prefix of the streamed
 * event channel: `ai-suggest:<job_id>:token` / `:done`.
 */
job_id: string, };
