// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Payload emitted on `ai-suggest:<job_id>:token`.
 */
export type AiSuggestTokenEvent = { job_id: string, delta: string, };
