// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Result of `agent_apply_continuity`.
 */
export type ApplyContinuityResultDto = { task_id: string, finding_index: number, 
/**
 * "rename" | "annotate"
 */
kind: string, pre_snapshot_id: string, applied_edit_ids: Array<string>, 
/**
 * Number of scenes whose text was rewritten (rename only; 0 for annotate).
 */
scenes_touched: number, from_term: string | null, to_term: string | null, };
