// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Result of `agent_apply_outline`.
 */
export type ApplyOutlineResult = { task_id: string, pre_snapshot_id: string, project_root_id: string, created_node_count: number, applied_edit_count: number, };
