// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Input to `validators_apply_fix` — a single auto-fix invocation.
 */
export type ApplyFixInput = { validator_id: string, node_id: string, };
