// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Input to the `agent_apply_copyedit` Tauri command (BACKLOG §E0d.5).
 *
 * Accepts one entry from a stored `CopyeditProposals` and applies it to
 * the live scene's `pm_doc`.  The orchestrator takes the mandatory
 * `pre_agent_edit` snapshot, mutates the scene, and inserts an
 * `agent_applied_edits` ledger row with `edit_kind = TextReplace`.
 */
export type ApplyCopyeditInput = { 
/**
 * `agent_tasks.id` of the copyeditor run that produced the proposal.
 */
task_id: string, 
/**
 * ULID of the scene to mutate.  The UI knows which scene the proposal
 * applies to (it dispatched the run).
 */
scene_id: string, 
/**
 * Index into `CopyeditProposals.edits` to accept.
 */
edit_index: number, };
