// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Input to `agent_apply_scene_drafter_fic`. Same shape as the
 * chapter-drafter apply input; kept distinct so the audit ledger reader
 * can dispatch on type.
 */
export type ApplySceneDrafterFicInput = { task_id: string, scene_id: string, };
