// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Input to `agent_apply_polish`. Polymorphic over stage — the orchestrator
 * reads the stored proposal's `stage_id` and writes the right audit
 * payload.
 */
export type ApplyPolishInput = { task_id: string, scene_id: string, };
