// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Input to the `agent_apply_outline` Tauri command (MZ-07).
 */
export type ApplyOutlineInput = { 
/**
 * ULID of the open project (matches the bundle's project id).
 */
project_id: string, 
/**
 * `agent_tasks.id` of the previously-completed outline-architect run.
 * The orchestrator looks up the persisted proposal via this id.
 */
task_id: string, 
/**
 * Title to use for the project-root node.  Usually the manifest title.
 */
project_title: string, };
