// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { BoilerplatePageDto } from "./BoilerplatePageDto";

/**
 * Input to `boilerplate_save`. Whole-list upsert — the saved list
 * replaces whatever is in `book:boilerplate_pages` memory.
 */
export type BoilerplateSaveInput = { pages: Array<BoilerplatePageDto>, };
