// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One scene's deterministic continuity findings, as surfaced to the UI.
 * Mirrors `booksforge_orchestrator::run::ContinuityScenePass` but
 * re-shapes the inner findings as JSON strings for IPC stability.
 */
export type ContinuityScenePassDto = { scene_id: string, scene_title: string, 
/**
 * JSON-serialised array of `ContinuityFinding`.  The UI parses on
 * demand — keeps this DTO simple and avoids a per-finding ts-rs
 * derivation.
 */
findings_json: string, finding_count: number, };
