// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type CoverAssetDto = { bundle_path: string, original_filename: string, size_bytes: bigint, mime_type: string, width_px: number | null, height_px: number | null, 
/**
 * RFC-3339 UTC timestamp.
 */
imported_at: string, };
