// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CoverAssetDto } from "./CoverAssetDto";

/**
 * Result of `cover_import` — echoes back the full `CoverSet` after
 * the import so the UI can re-render in one round-trip.
 */
export type CoverSetDto = { 
/**
 * Empty slot is `null` JSON, present slot is the asset.
 */
front: CoverAssetDto | null, back: CoverAssetDto | null, spine: CoverAssetDto | null, };
