// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Input for `project_create`.
 */
export type CreateProjectInput = { 
/**
 * Absolute path where the `*.booksforge/` bundle should be created.
 */
bundle_path: string, title: string, author: string, 
/**
 * Optional `genre` string (free-form tag for UI grouping).
 */
genre: string | null, };
