// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Input to `entity_bible_apply_proposals` (BACKLOG §F4).  Promotes
 * memory-curator's auto-extracted `EntityStub`s into real `Entity`
 * rows in the project's bible.
 */
export type EntityBibleApplyInput = { 
/**
 * `agent_tasks.id` of the memory-curator run that produced the
 * stubs (looked up via `agent_outputs`).
 */
task_id: string, 
/**
 * Indices into `MemoryRefreshProposals.new_entities` to accept.
 */
accepted_indices: Array<number>, };
