// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Result of `export_run` — single shape across all profiles.  EPUB
 * runs additionally include validation summary fields if EPUBCheck
 * was available; DOCX/PDF runs return them empty.
 */
export type ExportRunResult = { export_id: string, profile: string, output_path: string, bytes: bigint, hash: string, 
/**
 * True if EPUBCheck ran and reported zero ERROR/FATAL issues.
 * Always `true` for non-EPUB profiles.  False if EPUBCheck is
 * unavailable on this machine — `validation_message` carries the
 * reason so the UI can show "Local-only — install Java + EPUBCheck
 * to validate".
 */
validation_ok: boolean, validation_message: string | null, error_count: number, warning_count: number, };
