// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Input to the unified `export_run` command (Phase 6).
 *
 * `profile` is one of: `"markdown"`, `"docx"`, `"generic_epub"`,
 * `"kdp_ebook"`, `"trade_pdf_5x8"`, `"trade_pdf_6x9"`.  The wire form
 * is a string so the UI can drive it from a `<select>` without a
 * per-profile typed dispatch.
 */
export type ExportRunInput = { profile: string, output_path: string, 
/**
 * Genre-aware typography profile.  String form so the UI can drive
 * it from a `<select>`.  One of: `"fiction_trade_mass"`,
 * `"fiction_trade_standard"` (default), `"fiction_literary"`,
 * `"fiction_young_adult"`, `"non_fiction_practical"`,
 * `"non_fiction_memoir"`, `"academic"`.  Empty / unknown values
 * fall back to `fiction_trade_standard`.
 */
format_profile: string | null, };
