// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Input to `export_markdown`.
 */
export type ExportMarkdownInput = { 
/**
 * Absolute path the file will be written to.  The user picks this with
 * the OS save-file dialog (handled in the frontend).
 */
output_path: string, };
