// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One row from the `exports` ledger, IPC-safe.
 */
export type ExportHistoryEntry = { id: string, profile: string, output_path: string, hash: string, 
/**
 * ISO-8601 created_at.
 */
created_at: string, };
