// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ExportDependencyStatus } from "./ExportDependencyStatus";

/**
 * Aggregate response of `export_check_dependencies`.
 */
export type ExportDependencyReport = { items: Array<ExportDependencyStatus>, };
