// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type MemoryListInput = { 
/**
 * One of: "book" | "chapter" | "entity" | "style".
 */
scope: string, };
