// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type MemoryDeleteInput = { 
/**
 * Scope of the entry to delete ("book" | "chapter" | "entity" | "style").
 * Required because storage keys entries by (scope, key), not by ULID.
 */
scope: string, key: string, };
