// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Input for `node_create`.
 */
export type NodeCreateInput = { parent_id: string | null, kind: string, title: string, 
/**
 * LexoRank position string.
 */
position: string, status: string, target_words: number | null, };
