// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Input for `node_update` (partial — only mutable fields).
 */
export type NodeUpdateInput = { id: string, title: string | null, position: string | null, status: string | null, pov: string | null, beat: string | null, target_words: number | null, };
