// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One row from the `nodes` table, safe to send to the frontend.
 */
export type NodeInfo = { id: string, parent_id: string | null, 
/**
 * `"project"` | `"part"` | `"chapter"` | `"scene"` | `"front_matter"` | `"back_matter"`
 */
kind: string, title: string, position: string, 
/**
 * `"planned"` | `"drafting"` | `"revised"` | `"final"`
 */
status: string, pov: string | null, beat: string | null, target_words: number | null, word_count: number, created_at: string, updated_at: string, };
