// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Input for `project_open`.
 */
export type OpenProjectInput = { 
/**
 * Absolute path to an existing `*.booksforge/` bundle.
 */
bundle_path: string, };
