// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Returned by `project_create` and `project_open` on success.
 */
export type OpenProjectResult = { project_id: string, title: string, author: string, bundle_path: string, 
/**
 * Current project classification (Phase 4 of PRODUCT_ROADMAP_E2E.md).
 * `None` for projects created before BookKind landed; the desktop
 * app surfaces an onboarding overlay so the user can backfill it.
 */
book_kind: string | null, };
