// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Input to the `originality_scan_chapter` command — runs the local
 * plagiarism detector (n-gram match against the project's own corpus)
 * over every scene under `chapter_id`.  Local-only; nothing leaves the
 * device.  Online plagiarism API integration is opt-in and gated on a
 * separate consent flow (BACKLOG §E0d.11).
 */
export type OriginalityScanInput = { chapter_id: string, 
/**
 * Minimum n-gram length (in words) before an overlap counts.
 * Defaults to 12 (≈ one full clause).
 */
min_words: number | null, };
