// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Result returned by `agent_run_outline`.
 */
export type OutlineRunResult = { run_id: string, task_id: string, 
/**
 * "completed" | "invalid" | "error" | "cancelled"
 */
status: string, 
/**
 * JSON of `OutlineProposal` on success; null otherwise.
 */
proposal_json: string | null, error: string | null, 
/**
 * Raw model text — always returned so the UI can show it on failure.
 */
raw_output: string | null, };
