// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Peer-reviewer concern shaped for the frontend.
 */
export type PeerReviewConcernDto = { 
/**
 * "info" | "warning" | "error"
 */
severity: string, quote: string, reason: string, evidence: string, };
