// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PublishingMetadata } from "./PublishingMetadata";

export type PrepareForPublishingInput = { 
/**
 * Optional list of platforms to bundle. Empty = all three.
 * Each entry is `"kdp" | "google_play" | "apple_books"`.
 */
platforms: Array<string>, metadata_overrides: PublishingMetadata, };
