// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Input for `project_kind_set` (Phase 4 / Phase 5B). Updates the
 * open project's `book_kind` (manifest.toml + open-project state).
 */
export type ProjectKindSetInput = { 
/**
 * One of `"literary-fiction" | "genre-fiction" | "non-fiction" |
 * "memoir" | "childrens-book"`. Forgiving parse via
 * `BookKind::from_str` accepts snake-case + bare aliases.
 */
book_kind: string, };
