// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Input to `project_brief_save`. Persists the writer's manually-edited
 * `ProjectBrief` to book-scope memory (key `project_brief`) so the
 * orchestrator's `creative_profile` block picks it up on every agent
 * run. Round 5 of PRODUCT_ROADMAP_E2E.md.
 *
 * All fields are optional except the brief structure itself. Empty
 * arrays / null Options for the uniqueness fields are valid — they
 * signal "no signal here, render conservatively."
 */
export type ProjectBriefSaveInput = { 
/**
 * The full edited brief, serialised as JSON. Validated against the
 * `ProjectBrief` shape on the backend before write.
 */
brief_json: unknown, };
