// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One readiness checklist item. UI renders a colour-coded badge.
 */
export type ReadinessItem = { id: string, label: string, 
/**
 * `"PASS" | "WARN" | "FAIL" | "HUMAN_REQUIRED"`.
 */
status: string, detail: string, };
