// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One row in the recent-projects list (returned by `project_recent`).
 */
export type RecentProjectEntry = { id: string, path: string, name: string, 
/**
 * ISO-8601 timestamp string.
 */
last_opened: string, 
/**
 * `true` when the path no longer exists on disk.
 */
missing: boolean, };
