// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Returned by `recovery_check`.
 */
export type RecoveryStatus = { 
/**
 * Whether there are uncommitted pending saves in the recovery log.
 */
has_pending: boolean, 
/**
 * The node_id of the most recent uncommitted save (if any).
 */
node_id: string | null, 
/**
 * ISO-8601 timestamp of the pending save.
 */
pending_at: string | null, };
