// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Input to `agent_run_audience_mapper` (Phase C — Stage 2 output).
 *
 * Generates a Reader Expectation Map from the saved brief. Persists
 * to `book:audience_map` memory so downstream agents (scene drafter,
 * polish stack) can read it via `creative_profile`.
 */
export type RunAudienceMapperInput = { project_id: string, model: string | null, };
