// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type RunContinuityInput = { project_id: string, node_id: string, model: string, project_pov: string | null, prior_summary: string | null, high_confidence_mode: boolean, };
