// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Input to `agent_run_character_bible`.
 */
export type RunCharacterBibleInput = { project_id: string, 
/**
 * Number of chapters in the outline; each `CharacterCard.chapter_arc`
 * must have one entry per chapter.
 */
chapter_count: number, 
/**
 * Optional accepted-prose paragraphs the bible can derive measurable
 * voice traits from. Empty array = none.
 */
accepted_prose_samples: Array<string>, model: string, };
