// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type RunCopyeditInput = { project_id: string, node_id: string, model: string, 
/**
 * When true, the orchestrator dispatches the council's high-confidence
 * peer reviewers in addition to the always-on default-on pairings.
 */
high_confidence_mode: boolean, };
