// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type RunChapterDrafterInput = { project_id: string, node_id: string, scene_synopsis: string, chapter_purpose: string, project_pov: string, target_words: number, model: string, genre: string | null, tone: string | null, 
/**
 * Opt into the council's non-default-on peer reviewers.  See AGENTS.md §6.5.
 */
high_confidence_mode: boolean | null, };
