// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Input to `agent_run_concept_scorer` (Phase C — Stage 1 gate).
 *
 * Reads the brief from `book:project_brief` memory; no extra fields
 * required. `model` is auto-resolved when omitted — Light tier
 * (qwen3.5:9b) is the default. The agent returns a
 * `ConceptScoreProposal` (per-axis scores + composite + revisions).
 */
export type RunConceptScorerInput = { project_id: string, 
/**
 * Optional Ollama model tag. When `None` or empty, the backend
 * resolves the right tier automatically (Light for concept_scorer).
 */
model: string | null, };
