// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Input to `agent_run_intake_and_outline` (BACKLOG §E1).
 *
 * Chained workflow: free-text idea → intake agent → typed
 * `ProjectBrief` → outline-architect agent → `OutlineProposal`.
 * Counts as 2 of the workflow's ≤8 calls per run.
 */
export type RunIntakeAndOutlineInput = { project_id: string, idea_text: string, preferred_mode: string | null, target_chapter_count: number, genre_overlay: string | null, model: string, };
