// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type RunMemoryCuratorInput = { project_id: string, 
/**
 * "book" | "chapter" | "entity"
 */
scope: string, node_id: string | null, model: string, };
