// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Tier-2 ProposalValidator input — caller supplies the primary agent's
 * output and the orchestrator enriches with context.
 */
export type RunProposalValidatorInput = { project_id: string, primary_agent_id: string, 
/**
 * JSON-stringified primary agent output (what the user is reviewing).
 */
primary_output_json: string, context_excerpt: string, 
/**
 * JSON-stringified Tier-1 ProposalValidation (already computed by the
 * orchestrator on the primary call).
 */
tier_1_findings_json: string, model: string, };
