// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Input to `agent_run_scene_critic` — drives the per-scene critique-revise
 * loop. Returns a `SceneCritiqueProposal` (per-axis scores + targeted
 * edit instructions) the UI can show before invoking the reviser.
 */
export type RunSceneCriticInput = { project_id: string, scene_id: string, scene_text: string, scene_goal: string, scene_conflict: string, scene_reveal: string, 
/**
 * 4-6 axis names from the genre pack (e.g. for literary fiction:
 * `["scene_goal_clear", "specificity_of_perception", "voice_distinct",
 * "subtext_present", "image_freshness", "interiority_earned"]`).
 */
critic_axes: Array<string>, genre_label: string, voice_constraints: string, prior_summary: string, model: string, };
