// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Input to `agent_run_structure_critic` (Phase C — Stage 4 gate).
 *
 * The UI passes the outline to score as a JSON string (the same
 * shape that `agent_run_outline` returns in `proposal_json`). The
 * command loads the brief from `book:project_brief` and runs the
 * structure-critic agent against the pair. Auto-resolves to Medium
 * tier when `model` is None.
 */
export type RunStructureCriticInput = { project_id: string, 
/**
 * JSON string of `OutlineProposal`. The caller is responsible
 * for sourcing this from the in-memory preview state or from a
 * prior `agent_run_outline` result.
 */
outline_json: string, model: string | null, };
