// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Returned by `scene_load`.
 */
export type SceneLoadResult = { node_id: string, pm_doc: unknown, word_count: number, char_count: number, updated_at: string, };
