// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Input for `scene_save`.
 */
export type SceneSaveInput = { node_id: string, 
/**
 * ProseMirror JSON document (matches `SceneContent.pm_doc`).
 */
pm_doc: unknown, word_count: number, char_count: number, };
