// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Frontend-shaped snapshot record returned by `snapshot_create` / `_list`.
 */
export type SnapshotDto = { id: string, scope: string, scope_id: string | null, label: string | null, trigger: string, tree_hash: string, 
/**
 * ISO-8601 UTC.
 */
created_at: string, size_bytes: bigint, };
