// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Input to `snapshot_create`.
 */
export type SnapshotCreateInput = { 
/**
 * One of: "project" | "part" | "chapter" | "scene".
 */
scope: string, 
/**
 * ULID of the scoped node (omit for project scope).
 */
scope_id: string | null, label: string | null, 
/**
 * One of: "manual" | "auto" | "pre_ai" | "pre_export" | "pre_migration"
 * | "pre_agent_edit" | "crash_recovery".  The UI Snapshot button always
 * sends "manual".
 */
trigger: string, };
