// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Input to `snapshot_diff`.
 */
export type SnapshotDiffInput = { a: string, b: string, };
