// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { StylometricComponent } from "./StylometricComponent";

/**
 * Stylometric distance between two profiles. Score 0-10 (10 = identical).
 */
export type StylometricDistance = { distance_score_out_of_10: number, components: Array<StylometricComponent>, };
