// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Density-and-verdict report.
 */
export type TellsReport = { word_count: number, tell_count: number, density_per_1000: number, weighted_density_per_1000: number, by_severity_3: number, by_severity_2: number, by_severity_1: number, 
/**
 * `"PUBLISHABLE"` (weighted < 6), `"NEEDS_REVISION"` (6-12), or
 * `"AI_SMELL_HIGH"` (>12).
 */
verdict: string, by_category_json: string, };
