// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One detected fingerprint hit.
 */
export type TellHit = { start: number, end: number, matched: string, severity: number, category: string, why: string, suggested_replacement: string | null, };
