// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One validator finding shaped for the frontend.  Mirrors
 * `booksforge_domain::ValidatorIssue` but stringifies ULIDs and the
 * severity enum.
 */
export type ValidatorIssueDto = { validator_id: string, code: string, 
/**
 * "info" | "warning" | "error".
 */
severity: string, message: string, node_id: string | null, offset_from: number | null, offset_to: number | null, auto_fixable: boolean, };
