// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PeerReviewResultDto } from "./PeerReviewResultDto";
import type { ProposalValidationDto } from "./ProposalValidationDto";

export type VerificationReportDto = { primary_agent_id: string, primary_task_id: string, tier_1: ProposalValidationDto, tier_2: ProposalValidationDto | null, peer_reviews: Array<PeerReviewResultDto>, 
/**
 * "pass" | "warn" | "block"
 */
final_verdict: string, };
