// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type VocabEntryDto = { id: string, layer: string, term: string, display_term: string, 
/**
 * "prefer" | "avoid" | "replace".
 */
kind: string, replacement: string | null, rationale: string | null, 
/**
 * "starter" | "user" | "agent".
 */
source: string, created_at: string, updated_at: string, };
