// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Result of `vocab_apply_proposals`.  The lists name the rows actually
 * written — the UI shows a confirmation toast with the counts.
 */
export type VocabApplyResult = { task_id: string, additions_applied: number, modifications_applied: number, additions_skipped: number, modifications_skipped: number, };
