// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type VocabUpsertInput = { 
/**
 * Optional id — present when editing an existing entry.
 */
id: string | null, layer: string, term: string, display_term: string, 
/**
 * "prefer" | "avoid" | "replace".
 */
kind: string, replacement: string | null, rationale: string | null, };
