// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { VoiceProfile } from "./VoiceProfile";

export type VoiceAnchorGetResult = { profile: VoiceProfile | null, constraints_block: string | null, };
