// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SentenceLengthBucket } from "./SentenceLengthBucket";

/**
 * One bucket's measurement against its target band.
 */
export type BucketScore = { bucket: SentenceLengthBucket, actual_share: number, passes: boolean, };
