// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One bucket in a sentence-length distribution. `max_words` is
 * *inclusive*; use `u32::MAX` for an unbounded upper end. `target_share`
 * is the fraction of the prose's sentences that should fall in this
 * bucket (0..1). `tolerance` is the +/- band — `target=0.60,
 * tolerance=0.10` accepts anything in `[0.50, 0.70]`.
 */
export type SentenceLengthBucket = { min_words: number, max_words: number, target_share: number, tolerance: number, };
