// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One component of the stylometric distance score.
 */
export type StylometricComponent = { dim: string, delta_norm: number, weight: number, };
