// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { BucketScore } from "./BucketScore";

/**
 * Overall draft-vs-target score. `overall_passes` is true iff every
 * dimension is in band; otherwise `failed_dimensions` lists each miss
 * in human-readable form so the polish prompt can target them.
 */
export type VoiceScore = { bucket_scores: Array<BucketScore>, ttr_passes: boolean, 
/**
 * True iff `mattr_min` was 0.0 (unenforced), the prose was too
 * short for MATTR to be defined, or the measured MATTR-50 is at
 * or above the target floor.
 */
mattr_passes: boolean, em_dash_passes: boolean, repeated_opening_passes: boolean, long_sentence_passes: boolean, 
/**
 * Run #12 anti-bimodal-collapse check — true iff every 4+ sentence
 * paragraph touches at least `min_band_coverage_per_paragraph`
 * distinct length-buckets across its sentences.
 */
band_coverage_passes: boolean, 
/**
 * Smallest number of length-buckets touched by any 4+ sentence
 * paragraph. Useful diagnostic for the planner — directly says
 * "this paragraph collapsed into N bands."
 */
worst_paragraph_band_coverage: number, max_consecutive_repeated_openings: number, overall_passes: boolean, failed_dimensions: Array<string>, };
