// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SentenceLengthBucket } from "./SentenceLengthBucket";

/**
 * Prescriptive voice contract. All fields are *targets the draft must
 * satisfy*, not statistics measured from existing prose.
 */
export type VoiceTarget = { 
/**
 * Human-readable label rendered into the prompt directive
 * (e.g. `"literary fiction — Cormac McCarthy / Marilynne Robinson cluster"`).
 */
label: string, 
/**
 * Sentence-length distribution. Buckets need not be exhaustive (the
 * scorer only measures bucket coverage; uncovered ranges contribute
 * to neither pass nor fail).
 */
sentence_length_buckets: Array<SentenceLengthBucket>, 
/**
 * Type-token ratio floor (vocabulary richness, 0..1). Literary
 * norm is ~0.45+; Run #11's collapsed prose hit 0.303.
 *
 * **Length-biased.** For cross-run comparisons use [`Self::mattr_min`]
 * instead — TTR is here for back-compat only.
 */
type_token_ratio_min: number, 
/**
 * Moving-Average TTR (window 50) floor — the length-stable
 * counterpart to [`Self::type_token_ratio_min`]. Literature
 * suggests 0.66 as the threshold separating literary from
 * generic prose for this window size. Default `0.0` = unenforced.
 * FEATURE_HARDENING_PLAN.md §1.1.
 */
mattr_min: number, 
/**
 * Maximum em-dashes per 1000 words. The Run #11 critique flagged
 * em-dash overuse as a separate AI-tell; this cap lets a target
 * allow none, some, or many depending on the voice.
 */
em_dash_per_1000_max: number, 
/**
 * Maximum number of *consecutive* sentences that may begin with
 * the same 3-word opening clause. Anaphora is a real device but
 * past 4 repetitions becomes machine-like (Run #11 had 8 and 11).
 */
repeated_opening_max: number, 
/**
 * Companion cap for 2-token anaphora — `She fell. She rose. She
 * fell. She rose.` is invisible to the 3-token check (the third
 * token differs each time) but is the same machine-rhythm tell.
 * Default `0` = unenforced. FEATURE_HARDENING_PLAN.md §1.4.
 */
repeated_opening_max_2tok: number, 
/**
 * Companion cap for 4-token anaphora — `The hand on the door. The
 * hand on the lock. The hand on the chain.` Default `0` =
 * unenforced. FEATURE_HARDENING_PLAN.md §1.4.
 */
repeated_opening_max_4tok: number, 
/**
 * At least this many sentences in every paragraph (≥ 3 sentences;
 * FEATURE_HARDENING_PLAN.md §1.5 dropped the floor from 4 → 3)
 * must be ≥ 18 words long. Forces the long-sentence end of the
 * distribution to actually appear, not just be tolerated.
 */
min_long_sentences_per_paragraph: number, 
/**
 * **Anti-bimodal-collapse interleaving requirement.** Every
 * paragraph of 4+ sentences must touch at least this many
 * distinct length-buckets across its sentences. The Run #12
 * failure mode was 84% short / 0% medium / 16% long — the
 * drafter satisfied the aggregate distribution but skipped the
 * medium band entirely (one paragraph was 30 short sentences in
 * a row, others were one long run-on each). Setting this to 2
 * forces every long paragraph to interleave at least two of
 * {short, medium, long}; setting it to 3 forces all three.
 * Default `0` = unenforced.
 * FEATURE_HARDENING_PLAN-RUN12.md §1 + Run #12 quality review §8.
 */
min_band_coverage_per_paragraph: number, 
/**
 * If true, at least one dialogue sentence is required. Scene-card
 * driven — most scenes have dialogue, some interior scenes don't.
 * **Note:** for literary fiction this counts interior monologue
 * rendered as dialogue (`"What was she doing?"` she thought).
 * Run #12 produced zero dialogue and the scene goal would have
 * been improved by 1-2 lines of internal speech.
 */
require_dialogue: boolean, };
