// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * The application version returned by the `app_version` Tauri command.
 *
 * Corresponds to the semver fields in `Cargo.toml [workspace.package]`.
 */
export type AppVersion = { major: number, minor: number, patch: number, 
/**
 * Pre-release tag (e.g. `"alpha.1"`).  Always serialised — TS sees
 * `string | null`.  Earlier versions used `skip_serializing_if`
 * which ts-rs 10 can't parse; emitting `null` is just as clear and
 * keeps the bindings deterministic.
 */
pre: string | null, };
