// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One entry in the model list returned by `ollama_list_models`.
 * Merges the curated registry entry with local availability information.
 */
export type ModelListEntry = { 
/**
 * Ollama pull tag.
 */
id: string, display_name: string, family: string, 
/**
 * Approximate download size in bytes.
 */
size_bytes: bigint, 
/**
 * Minimum RAM (GB) required.
 */
ram_min_gb: number, context_window: number, recommended_for: Array<string>, strengths: Array<string>, notes: string, default_for_modes: Array<string>, 
/**
 * Whether this model appears in the picker (`false` = internal/smoke only).
 */
official: boolean, 
/**
 * Whether the model is already installed locally.
 */
is_installed: boolean, 
/**
 * Local digest hash (sha256:…), present when installed.
 */
digest: string | null, };
