// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Result of `ollama_probe` — full status of the local Ollama environment.
 */
export type OllamaProbeResult = { 
/**
 * Whether the Ollama HTTP API is reachable.
 */
api_reachable: boolean, 
/**
 * Ollama server version, if reachable.
 */
version: string | null, 
/**
 * Whether an Ollama binary was found on disk (may not be running).
 */
binary_found: boolean, 
/**
 * Detected system RAM in GB (`null` if detection failed).
 */
ram_gb: number | null, };
