// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Result of `ollama_status` — minimal Ollama health check.
 *
 * Distinct from `OllamaProbeResult`: the *probe* command also detects
 * the binary on disk and the system RAM, while *status* is the
 * fast/cheap path used by the always-visible status indicator.
 */
export type OllamaStatusResponse = { 
/**
 * Whether the Ollama HTTP API is currently reachable on the
 * configured loopback host.
 */
running: boolean, 
/**
 * Ollama server version, if reachable.
 */
version: string | null, };
