// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Progress payload emitted as a Tauri event during `ollama_pull`.
 * Event name: `"ollama:pull-progress"`.
 */
export type PullProgressPayload = { model: string, status: string, completed: bigint | null, total: bigint | null, };
