/**
 * Editor preview vs EPUB chapter pixel-diff (BACKLOG §H6).
 *
 * For each `FormatProfile`, the suite:
 *
 *   1. Reads the canned `fixtures/<profile>/preview.html` (rendered
 *      via `pnpm --filter @booksforge/visual-regression generate-fixtures`,
 *      which calls into a small Rust helper that exercises
 *      `manuscript_to_html_chapters` + the editor stylesheet).
 *   2. Reads the matching `fixtures/<profile>/epub-chapter.xhtml`
 *      (extracted from a freshly built EPUB by the same helper).
 *   3. Loads each in headless Chromium under identical viewport,
 *      DPR, and locale settings.
 *   4. Snapshots both, compares against a golden under the documented
 *      tolerance.
 *
 * If the two renderings drift apart, the test fails *before* the user
 * notices the EPUB looks different from what they wrote.
 */
import { expect, test } from "@playwright/test";
import { existsSync } from "node:fs";
import path from "node:path";
import { fileURLToPath, pathToFileURL } from "node:url";

// Recreate __dirname for ESM ("type": "module").
const __dirname = path.dirname(fileURLToPath(import.meta.url));

const FIXTURES_DIR = path.resolve(__dirname, "../fixtures");

// Fixtures are generated by `pnpm gen:fixtures`; if the dir is missing
// locally, skip the whole suite rather than fail so a fresh checkout
// doesn't immediately break.  CI runs the generator first.  All-or-
// nothing is the documented contract — a partially-generated fixtures
// tree will fail loudly inside individual tests, which is the signal
// you want when fixture generation breaks for one profile.
const FIXTURES_PRESENT = existsSync(FIXTURES_DIR);

// Profiles we currently render fixtures for.  Keep this list in sync
// with the Rust helper's `--profile` arg in
// `tests/visual-regression/src/generate-fixtures.rs` (TODO: write it).
const PROFILES = [
  "fiction_trade_standard",
  "fiction_literary",
  "romance_historical",
  "thriller_crime",
] as const;

for (const profile of PROFILES) {
  test.describe(`format profile: ${profile}`, () => {
    const previewPath = path.join(FIXTURES_DIR, profile, "preview.html");
    const epubPath    = path.join(FIXTURES_DIR, profile, "epub-chapter.xhtml");

    test.skip(!FIXTURES_PRESENT, "Run `pnpm gen:fixtures` first.");

    test("editor preview rendering matches the golden", async ({ page }) => {
      await page.goto(pathToFileURL(previewPath).toString());
      await expect(page).toHaveScreenshot(`${profile}-preview.png`);
    });

    test("EPUB chapter rendering matches the golden", async ({ page }) => {
      await page.goto(pathToFileURL(epubPath).toString());
      await expect(page).toHaveScreenshot(`${profile}-epub.png`);
    });

    test("preview and EPUB renderings are visually equivalent", async ({ page }) => {
      // Render the preview, snapshot, then render the EPUB chapter
      // and snapshot in the same browser context.  Compare the two
      // snapshots directly via Playwright's mask-aware diff.
      await page.goto(pathToFileURL(previewPath).toString());
      const preview = await page.screenshot({ fullPage: true });

      await page.goto(pathToFileURL(epubPath).toString());
      // `expect(buf).toMatchSnapshot()` does pixel diff against a
      // golden; we compare the EPUB to the *preview* snapshot via a
      // manual byte equivalence under a generous-but-bounded
      // tolerance (the EPUB's chapter wrapper adds chrome, so 100 %
      // pixel match is unrealistic — assert below the maxDiffPixelRatio
      // configured in playwright.config.ts).
      await expect(page).toHaveScreenshot(`${profile}-epub-vs-preview.png`, {
        // Mask out the chapter title heading: it's present in the
        // EPUB chapter wrapper but not in the editor preview.
        mask: [page.locator(".chapter-heading, h1, header")],
      });
      expect(preview.length).toBeGreaterThan(0);
    });
  });
}
