// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Result of `bibles_save`.
 */
export type BiblesSaveResult = { characters_written: number, characters_removed: number, world_locations_written: number, world_locations_removed: number, 
/**
 * Names of `world:*` book-scope keys that were written.
 */
world_fields_written: Array<string>, };
