// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Result of `bibles_load`. Mirrors the shape the UI form needs:
 * the typed CharacterCards in their existing order plus a
 * reconstructed WorldBibleProposal (or empty when no world fields
 * have been written yet).
 */
export type BiblesLoadResult = { 
/**
 * One entry per character currently in entity-scope memory under
 * the `character:*` key prefix. Order = oldest-first by creation.
 */
characters: unknown[], 
/**
 * Reconstructed world bible. `null` if no world entries exist
 * at all (UI shows a "set up world bible" CTA in that case).
 */
world: unknown | null, 
/**
 * `true` when entity-scope memory contains at least one
 * `character:*` entry. The book pipeline reads this to decide
 * whether to skip the character-bible stage.
 */
has_character_bible: boolean, 
/**
 * Same for the world bible (any `entity:location:*` or
 * `book:world:*` entry counts).
 */
has_world_bible: boolean, };
