// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Input to `bibles_save`. Either array can be `None` to leave that
 * half of the bible untouched (so the UI can save just characters
 * without overwriting the world bible, and vice versa). When an
 * array IS supplied, it is treated as the authoritative full list:
 * characters / locations not in the new list are removed from
 * memory.
 */
export type BiblesSaveInput = { 
/**
 * New full list of CharacterCards. `None` = don't touch
 * character entries.
 */
characters: unknown[] | null, 
/**
 * New full WorldBibleProposal. `None` = don't touch world entries.
 */
world: unknown | null, };
