// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type BookSceneStageResult = { scene_id: string, scene_title: string, status: string, word_count: number, elapsed_s: number, note: string, };
