// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One stage of the pipeline. The UI uses these to render per-stage
 * status badges as the workflow progresses.
 */
export type PipelineStageResult = { 
/**
 * `"draft" | "critic" | "polish:dialogue" | "polish:metaphor" |
 * "polish:voice" | "polish:scene_tension" | "tells_scan"`.
 */
stage: string, 
/**
 * `"completed" | "skipped" | "failed"`.
 */
status: string, 
/**
 * task_id for an LLM stage (so the UI can fetch the proposal_json
 * and offer a per-stage Apply); empty for `tells_scan`.
 */
task_id: string, 
/**
 * Free-text hint surfaced to the user. For the critic: the
 * `weakest_axis` and `overall_one_liner`. For tells: the verdict +
 * density.
 */
summary: string, 
/**
 * Wall-clock seconds for this stage (rounded to 1 decimal).
 */
elapsed_s: number, };
