// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { BookSceneStageResult } from "./BookSceneStageResult";

/**
 * Per-stage result for the book pipeline. The UI uses this to render
 * a checklist of completed stages. The `scenes_drafted` array carries
 * one entry per scene that the drafter touched.
 */
export type RunBookPipelineResult = { project_id: string, character_bible_status: string, world_bible_status: string, 
/**
 * One entry per scene, in document order. `status` is one of
 * `"completed"`, `"skipped"`, `"failed"`, or `"cancelled"`.
 */
scenes: Array<BookSceneStageResult>, total_elapsed_s: number, };
