// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Input to `agent_run_book_pipeline`. Drives the full intake →
 * bibles → per-scene drafter chain in a single Tauri call so the
 * writer doesn't have to manually trigger each agent from the
 * Agents panel after the outline lands.
 */
export type RunBookPipelineInput = { project_id: string, 
/**
 * When true (default), scenes that already have prose
 * (`scene_content.word_count > 0`) are skipped — so the user can
 * re-run the pipeline after editing one scene without losing
 * hand-edits to others. Set `false` to overwrite every scene
 * (a snapshot is taken before each apply, so it's reversible).
 */
skip_already_drafted_scenes: boolean, 
/**
 * Hard cap on how many scenes to draft in this run. `None` =
 * no cap (drafts every scene in the project's outline).
 * Useful for "just generate Chapter 1" by passing 3-4.
 */
max_scenes: number | null, };
