// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Input to `agent_run_full_scene_pipeline`. Drafts a fiction scene
 * using the project's `book_kind` to drive genre-correct prompts +
 * polish-stack ordering, then runs the 4-stage polish stack, and
 * finishes with an AI-tells density measurement.
 */
export type RunFullScenePipelineInput = { project_id: string, node_id: string, scene_goal: string, scene_conflict: string, scene_reveal: string, target_words: number, chapter_pov: string, 
/**
 * Default model for stages that don't specify their own. Acts as
 * the fallback for both the heavy (drafter / polish) and the
 * light (critic) tier when `model_critic` is unset. Most callers
 * will pin this to a 27B-class model.
 */
model: string, 
/**
 * O2 of `docs/VSM_LLM_OPTIMIZATION.md` — optional faster model
 * used for the scene-critic pass. The critic's job is structural
 * scoring + targeted edit suggestions, not prose generation, so
 * a smaller faster model (e.g. `qwen3.5:9b`) shaves ~20–30% off
 * total wall-clock without measurable quality loss. Falls back
 * to `model` when unset.
 */
model_critic: string | null, 
/**
 * O1 of `docs/VSM_LLM_OPTIMIZATION.md` — when true (the
 * default), polish stages whose deterministic skip-detector
 * reports "no work to do" are skipped instead of running the
 * LLM. Set to `false` to force every stage to run regardless
 * (useful for benchmarking). Saves ~30–40% wall-clock on a
 * typical literary scene where 1–2 of the 4 polish stages are
 * no-ops.
 */
skip_empty_polish_stages: boolean, 
/**
 * When true, the workflow stops after the scene-critic pass and
 * returns its findings — useful for "draft, then let me decide
 * whether to polish." Default `false` (run the full pipeline).
 */
stop_after_critic: boolean, };
