// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PipelineStageResult } from "./PipelineStageResult";

export type RunFullScenePipelineResult = { project_id: string, node_id: string, 
/**
 * The book_kind used to drive prompt + polish-stack ordering.
 */
book_kind: string, stages: Array<PipelineStageResult>, 
/**
 * Aggregate AI-tells density on the final polished prose, rendered
 * as the verdict string ("PUBLISHABLE" / "NEEDS_REVISION" / "AI_SMELL_HIGH").
 */
final_tells_verdict: string, 
/**
 * Total wall-clock seconds across every stage.
 */
total_elapsed_s: number, };
