// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Input to `save_diagnostic_bundle`.
 */
export type SaveDiagnosticBundleInput = { 
/**
 * Absolute path the bundle should be written to.  User picks via
 * the OS save-file dialog (extension `.zip`).
 */
output_path: string, };
