// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Tagged-union error returned by every Tauri IPC command.
 *
 * Rules:
 * - Add a new variant rather than using `Internal` for a known failure mode.
 * - Never put raw stack traces or file paths in the payload — they leak internals
 *   to the frontend and to any crash report.
 * - The `kind` discriminant is the TypeScript type tag.
 */
export type BooksForgeError = { "kind": "NotFound", "payload": { resource: string, } } | { "kind": "Validation", "payload": { message: string, } } | { "kind": "Io", "payload": { message: string, } } | { "kind": "Storage", "payload": { message: string, } } | { "kind": "AgentRuntimeUnavailable", "payload": { reason: string, } } | { "kind": "Cancelled" } | { "kind": "SchemaTooNew", "payload": { required_min: string, running: string, } } | { "kind": "Internal", "payload": { message: string, } };
