// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Periodic progress event emitted at ~4 Hz while a long-running
 * agent (chapter-drafter, dev-editor) is streaming tokens from
 * Ollama.  The frontend overlay uses this to show "342 tokens · 18 t/s".
 *
 * Volume: ~4 events/sec while active.  Auto-stops on
 * `agent-run-completed`.  Other agents (intake, vocab, memory-curator)
 * don't emit this — they're fast enough that elapsed time alone is
 * adequate feedback.
 */
export type AgentRunProgressEvent = { run_id: string, 
/**
 * Cumulative tokens received from Ollama since dispatch.
 */
tokens: number, 
/**
 * Wall-clock milliseconds since dispatch.  Frontend computes
 * tokens/sec = tokens / (elapsed_ms/1000).
 */
elapsed_ms: number, };
