// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { VerificationReportDto } from "./VerificationReportDto";

/**
 * Generic agent-run result shape used by the per-agent commands.  The
 * `proposal_json` carries the typed output (e.g. `CopyeditProposals`,
 * `ContinuityReport`) as a JSON string so the TypeScript side can
 * `JSON.parse` it into its own typed view.
 */
export type AgentRunResultDto = { run_id: string, task_id: string, 
/**
 * "completed" | "invalid" | "error" | "cancelled"
 */
status: string, agent_id: string, proposal_json: string | null, verification: VerificationReportDto, error: string | null, raw_output: string | null, };
