// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Event payload emitted on `agent-run-completed`.
 */
export type AgentRunCompletedEvent = { run_id: string, agent_id: string, 
/**
 * `"completed"` | `"cancelled"` | `"error"`
 */
status: string, error: string | null, 
/**
 * ISO-8601 timestamp when the dispatch finished.
 */
finished_at: string, };
