// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Input to `agent_cancel`.  Cancel is best-effort: a cancelled run
 * stops at the next sink callback or retry boundary inside the
 * runner; in-flight HTTP requests to Ollama are torn down via the
 * existing `CancelToken` plumbing.
 */
export type AgentCancelInput = { run_id: string, };
