// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Result of `ai_apply`.
 */
export type AiApplyResult = { ai_call_id: string, pre_snapshot_id: string, 
/**
 * ISO-8601 UTC timestamp.
 */
applied_at: string, };
