// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Input to `ai_apply`.
 */
export type AiApplyInput = { ai_call_id: string, 
/**
 * The text the user accepted in the diff panel.  Usually equal to the
 * `full_text` from the done event but the user may have edited it.
 */
accepted_text: string, 
/**
 * "replace" (Sharpen / Rephrase) or "append" (Continue).
 */
op: string, };
