// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Payload emitted on `ai-suggest:<job_id>:done`.
 */
export type AiSuggestDoneEvent = { job_id: string, 
/**
 * "ok" | "cancelled" | "error".
 */
status: string, 
/**
 * `ai_calls.id` — the audit row that was just written.  Always present
 * regardless of status, since the audit row is always persisted.
 */
ai_call_id: string, 
/**
 * Full accumulated text (may be partial when `status != "ok"`).
 */
full_text: string, duration_ms: bigint, error: string | null, };
