// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Input to `ai_suggest`.
 */
export type AiSuggestInput = { 
/**
 * The scene node the call runs against.
 */
node_id: string, 
/**
 * One of: "sharpen" | "continue" | "rephrase".
 */
preset: string, 
/**
 * The selected passage (or current paragraph when no selection).
 */
scope_text: string, 
/**
 * Ollama model tag.  When omitted the project default is used.
 */
model: string | null, 
/**
 * Optional context the UI may pass through (e.g. preceding paragraphs
 * for "continue", tone target for "rephrase").  Stringified JSON object
 * merged into the prompt template variables.
 */
options_json: string | null, };
