// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Result of `agent_apply_polish`.
 */
export type ApplyPolishResultDto = { task_id: string, scene_id: string, 
/**
 * Which stage was applied (`"dialogue" | "metaphor" | "voice" | "scene_tension"`).
 */
stage: string, pre_snapshot_id: string, applied_edit_id: string, previous_hash: string, new_hash: string, new_word_count: number, new_char_count: number, };
