// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Input to the `agent_apply_continuity` Tauri command (BACKLOG §E0d.7).
 * Accepts one finding from a stored `ContinuityReport` and applies its
 * `proposed_fix` (rename across scope, or annotate via memory upsert).
 */
export type ApplyContinuityInput = { project_id: string, task_id: string, finding_index: number, };
