// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Result of `agent_apply_copyedit`.
 */
export type ApplyCopyeditResult = { task_id: string, edit_index: number, scene_id: string, pre_snapshot_id: string, applied_edit_id: string, 
/**
 * `true` if the original char range no longer matched and a unique
 * `before`-substring search was used instead.  UI surfaces a hint so
 * the user can re-verify after concurrent edits.
 */
used_fallback_search: boolean, };
