// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Input to `agent_apply_world_bible`.
 */
export type ApplyWorldBibleInput = { task_id: string, };
