// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Input to `agent_apply_character_bible`.
 */
export type ApplyCharacterBibleInput = { task_id: string, };
