// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Result of `agent_apply_world_bible`.
 */
export type ApplyWorldBibleResultDto = { task_id: string, pre_snapshot_id: string, applied_edit_ids: Array<string>, location_names: Array<string>, book_scope_keys: Array<string>, };
