// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Result of `agent_apply_character_bible`.
 */
export type ApplyCharacterBibleResultDto = { task_id: string, pre_snapshot_id: string, applied_edit_ids: Array<string>, character_names: Array<string>, memory_keys: Array<string>, };
