// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Result of `validators_apply_fix`.
 */
export type ApplyFixResult = { validator_id: string, node_id: string, 
/**
 * Number of text nodes the fix mutated.  Zero is a successful no-op.
 */
fixes_applied: number, };
