// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Input to the `agent_apply_chapter_drafter` Tauri command (BACKLOG §A9).
 *
 * Accepts a previously-stored `SceneDraftProposal` and writes its `pm_doc`
 * into the live scene's content. The orchestrator takes the mandatory
 * `pre_agent_edit` snapshot, mutates the scene, and inserts an
 * `agent_applied_edits` ledger row with `edit_kind = TextReplace`.
 *
 * Replaces the prior session's UI-only Apply path which bypassed the
 * orchestrator and the audit ledger.
 */
export type ApplyChapterDrafterInput = { 
/**
 * `agent_tasks.id` of the chapter-drafter run that produced the proposal.
 */
task_id: string, 
/**
 * ULID of the scene to mutate.
 */
scene_id: string, };
