// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Input to the `agent_apply_humanization` Tauri command (BACKLOG §E0d.6).
 * Same shape as `ApplyCopyeditInput` — a separate struct keeps the
 * command surface explicit so the UI doesn't muddle the two flows.
 */
export type ApplyHumanizationInput = { task_id: string, scene_id: string, edit_index: number, };
