// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Result of `agent_apply_chapter_drafter`.
 */
export type ApplyChapterDrafterResultDto = { task_id: string, scene_id: string, pre_snapshot_id: string, applied_edit_id: string, 
/**
 * blake3 of the scene's `pm_doc` BEFORE the apply. Empty when the scene
 * had never been saved before.
 */
previous_hash: string, 
/**
 * blake3 of the scene's new `pm_doc`.
 */
new_hash: string, new_word_count: number, new_char_count: number, };
