// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs).
// Do not edit this file manually.

export interface AppVersion {
  major: number;
  minor: number;
  patch: number;
  pre: string | null;
}
