// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One boilerplate page as passed across IPC. Mirrors
 * `booksforge_domain::BoilerplatePage` field-for-field.
 */
export type BoilerplatePageDto = { id: string, 
/**
 * `"title_page" | "copyright" | "dedication" | "epigraph"
 * | "foreword" | "preface" | "acknowledgments" | "about_author"
 * | "also_by" | "back_cover_blurb" | "other"`.
 */
kind: string, title: string, body_md: string, order: number, include_in_export: boolean, };
