// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs).
// Do not edit this file manually.

export type BooksForgeError =
  | { kind: "not_found";               payload: { id: string } }
  | { kind: "validation";              payload: { field: string; message: string } }
  | { kind: "io";                      payload: { path: string; message: string } }
  | { kind: "storage";                 payload: { message: string } }
  | { kind: "agent_runtime_unavailable"; payload: { reason: string } }
  | { kind: "cancelled" }
  | { kind: "schema_too_new";          payload: { db_version: number; app_version: number } }
  | { kind: "internal";                payload: { message: string } };
