// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Input to `cover_import`. The frontend passes an absolute filesystem
 * path the user picked from a file dialog plus which slot to import
 * it into ("front" | "back" | "spine"). The command copies the file
 * into `<bundle>/assets/cover-<slot>.<ext>` and persists the
 * resulting `CoverAsset` into the project's `book:cover_set` memory
 * entry.
 */
export type CoverImportInput = { 
/**
 * Absolute path to the source image on the user's filesystem.
 */
source_path: string, 
/**
 * Which cover slot: "front" | "back" | "spine".
 */
slot: string, };
