// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Input for `project_create`.
 */
export type CreateProjectInput = { 
/**
 * Absolute path where the `*.booksforge/` bundle should be created.
 */
bundle_path: string, title: string, author: string, 
/**
 * Optional `genre` string (free-form tag for UI grouping).
 */
genre: string | null, 
/**
 * Project classification — drives the workflow router (per-genre
 * prompts, polish-stack ordering, rubric weights). Set by the
 * NewProjectWizard's first step (Phase 5 of PRODUCT_ROADMAP_E2E.md).
 * Optional for backwards compatibility with the prior wizard;
 * `None` triggers the post-create onboarding overlay.
 */
book_kind: string | null, };
