// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Result of `entity_bible_apply_proposals`.
 */
export type EntityBibleApplyResult = { task_id: string, inserted: number, skipped: number, };
