// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Status of an external binary the export pipeline depends on.
 * Surfaced to the UI so the user can see "Pandoc 3.5.0" vs
 * "Pandoc not found — install to enable DOCX/PDF" without dispatching
 * an export to discover it.
 */
export type ExportDependencyStatus = { 
/**
 * Identifier: `"pandoc"` | `"java"` | `"epubcheck"`.
 */
id: string, 
/**
 * Display name (e.g. "Pandoc").
 */
name: string, 
/**
 * True if the binary / JAR was found.
 */
found: boolean, 
/**
 * Resolved path (binary) when found.  Empty when missing.
 */
path: string, 
/**
 * Version string when probable; empty when not.
 */
version: string, 
/**
 * Profiles unlocked by this dependency.  UI uses to grey out
 * disabled cards.
 */
unlocks: Array<string>, 
/**
 * One-line hint for the user when the dependency is missing
 * (where to download / how to install).
 */
install_hint: string, };
