// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Result of `export_markdown` — counters useful for the success toast and
 * sanity checks.
 */
export type ExportMarkdownResult = { export_id: string, output_path: string, bytes: bigint, part_count: number, chapter_count: number, scene_count: number, word_count: number, 
/**
 * blake3 hex of the rendered bytes (matches `exports.hash`).
 */
hash: string, };
