// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ValidatorIssueDto } from "./ValidatorIssueDto";

/**
 * Result of the export-gate evaluation that the UI can show before
 * allowing the export command.
 */
export type ExportGateDto = { 
/**
 * "pass" | "warn" | "block".
 */
outcome: string, errors: Array<ValidatorIssueDto>, warnings: Array<ValidatorIssueDto>, };
