// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type MemoryEntryDto = { id: string, 
/**
 * "book" | "chapter" | "entity" | "style".
 */
scope: string, key: string, 
/**
 * JSON-stringified value — the structure depends on scope.
 */
value_json: string, agent_id: string, 
/**
 * ISO-8601 UTC.
 */
created_at: string, updated_at: string, };
