// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type MemoryUpsertInput = {
/**
 * Optional id — when present this is an edit; when absent this is a
 * fresh row and storage assigns the id.
 */
id: string | null,
/**
 * One of: "book" | "chapter" | "entity" | "style".
 */
scope: string, key: string,
/**
 * JSON-stringified value — must parse as JSON.
 */
value_json: string, };
