// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One node-level diff entry returned by `snapshot_diff`.
 */
export type NodeDiffDto = { node_id: string, 
/**
 * "added" | "removed" | "changed"
 */
kind: string, title: string, };
