// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs).
// Do not edit this file manually.

export interface NodeInfo {
  id: string;
  parent_id: string | null;
  kind: string;
  title: string;
  position: string;
  status: string;
  pov: string | null;
  beat: string | null;
  target_words: number | null;
  word_count: number;
  created_at: string;
  updated_at: string;
}
