// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs).
// Do not edit this file manually.

export interface NodeUpdateInput {
  id: string;
  title: string | null;
  position: string | null;
  status: string | null;
  pov: string | null;
  beat: string | null;
  target_words: number | null;
}
