// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs).
// Do not edit this file manually.

export interface NodeCreateInput {
  parent_id: string | null;
  kind: string;
  title: string;
  position: string;
  status: string;
  target_words: number | null;
}
