// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Input for `node_move` — change a node's parent and position
 * in one transaction. Added so the binder can drag a scene from
 * one chapter into another without exposing `parent_id` on the
 * existing `node_update` (whose contract has never accepted it).
 *
 * Same-parent reorder is also supported by passing the existing
 * `parent_id` value — but for that case the frontend should still
 * prefer `node_update` since it's the established pattern; this
 * command is specifically for the cross-parent move.
 */
export type NodeMoveInput = { id: string, 
/**
 * New parent node id. `None` is rejected — moves to the
 * project root are not allowed because the project root is a
 * singleton (`kind = "project"`) and only the project itself
 * sits there.
 */
new_parent_id: string, 
/**
 * New LexoRank position string. The frontend computes this
 * via `lib/lexorank.positionBetween` against the destination
 * parent's existing children.
 */
new_position: string, };
