// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs).
// Do not edit this file manually.

export interface OpenProjectResult {
  project_id: string;
  title: string;
  author: string;
  bundle_path: string;
}
