// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { OverlapHitDto } from "./OverlapHitDto";

/**
 * Result returned by `originality_scan_chapter`.
 */
export type OriginalityScanResult = { chapter_id: string, scenes_scanned: number, min_words: number, hits: Array<OverlapHitDto>, };
