// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One detected verbatim overlap, mirrored from
 * `booksforge_validator::OverlapHit` for IPC.
 */
export type OverlapHitDto = { 
/**
 * "source" | "prior_scene"
 */
kind: string, scene_id: string, scene_title: string, output_from: number, output_to: number, words: number, quote: string, 
/**
 * Which other scene (within the project) the span matches.  Empty
 * when the scan was against an external source.
 */
matched_scene_id: string, matched_scene_title: string, };
