// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PeerReviewConcernDto } from "./PeerReviewConcernDto";

export type PeerReviewResultDto = { reviewer_agent_id: string, primary_task_id: string, 
/**
 * "fact_fidelity" | "voice_preservation" | "ai_tell_residue" |
 * "name_pov_preservation" | "structural_purpose" | "memory_consistency" |
 * "emotional_clarity"
 */
focus: string, 
/**
 * "pass" | "warn" | "block"
 */
verdict: string, concerns: Array<PeerReviewConcernDto>, recommendation: string, };
