// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ReadinessItem } from "./ReadinessItem";

export type PlatformReadiness = { platform: string, output_dir: string, items: Array<ReadinessItem>, uploadable: boolean, };
