// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PlatformReadiness } from "./PlatformReadiness";

export type PrepareForPublishingResult = { project_id: string, platforms: Array<PlatformReadiness>, elapsed_s: number, };
