// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Result of `project_brief_save` and `project_brief_load`. The
 * `value_json` field is the brief itself; `loaded` is false when no
 * brief has ever been saved for this project (i.e. the project is
 * pre-intake).
 */
export type ProjectBriefDto = { loaded: boolean, brief_json: unknown, 
/**
 * Audit-ledger origin of the saved brief. Surfaced in the
 * BriefEditorPanel so the writer knows where the data came from
 * — `"wizard"` (collected by the New Project wizard before
 * outline generation), `"intake"` (extracted by the intake
 * agent from a free-form idea), `"user-edit"` (manually saved
 * from the Brief panel), or empty for never-saved.
 */
source: string, 
/**
 * ISO-8601 timestamp of the last save. Empty for never-saved.
 */
updated_at: string, };
