// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Result of `project_kind_set`.
 */
export type ProjectKindSetResult = { project_id: string, book_kind: string, };
