// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ValidationCheckDto } from "./ValidationCheckDto";

export type ProposalValidationDto = { 
/**
 * "pass" | "warn" | "block"
 */
verdict: string, checks: Array<ValidationCheckDto>, summary: string, tier_2_ran: boolean, };
