// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type PublishingMetadata = { subtitle: string | null, description: string | null, short_description: string | null, 
/**
 * 7+ keywords for KDP / Google Play / Apple Books search.
 */
keywords: Array<string> | null, 
/**
 * BISAC subject codes (e.g. "FIC009000 FICTION / Fantasy / General").
 */
bisac_codes: Array<string> | null, age_range: string | null, language: string | null, isbn: string | null, price_usd: string | null, publication_date: string | null, publisher: string | null, rights_statement: string | null, };
