// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs).
// Do not edit this file manually.

export type PullProgressPayload = {
  model: string;
  status: string;
  completed: number | null;
  total: number | null;
};
