// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs).
// Do not edit this file manually.

export interface RecentProjectEntry {
  id: string;
  path: string;
  name: string;
  /** ISO-8601 timestamp string. */
  last_opened: string;
  /** `true` when the path no longer exists on disk. */
  missing: boolean;
}
