// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Input for `project_recent_remove`.  Removes a single entry from
 * `~/.booksforge/settings.toml`'s recent-projects list.  Does NOT
 * delete the bundle on disk — only the entry in the picker.
 */
export type RecentRemoveInput = { 
/**
 * Absolute bundle path of the entry to remove (matches the
 * `path` field returned by `project_recent`).
 */
path: string, };
