// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs).
// Do not edit this file manually.

export interface RecoveryStatus {
  has_pending: boolean;
  node_id: string | null;
  pending_at: string | null;
}
