// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Input for `reveal_in_finder` — opens the host OS's file manager
 * with the given path highlighted (or its parent on Linux where
 * the highlight protocol isn't standardised). Used by the recents
 * list's "Reveal" affordance.
 */
export type RevealInFinderInput = { 
/**
 * Absolute path to reveal. Need not be a `.booksforge/` bundle
 * — any existing path works.
 */
path: string, };
