// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Input to `agent_run_character_critic` (Phase C — Stage 3 gate).
 *
 * Reads the saved character bible (entity scope `character:*` keys)
 * and the brief; returns a per-card 5-axis score + cross-card
 * findings + targeted edits. No new fields beyond project_id since
 * the agent reads everything from memory.
 */
export type RunCharacterCriticInput = { project_id: string, model: string | null, };
