// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Input to `agent_run_developmental_review` (BACKLOG §F2).  Chained
 * chapter-level review: 1 LLM call (dev_editor) + per-scene
 * deterministic continuity linter (free, no LLM).
 */
export type RunDevelopmentalReviewInput = { project_id: string, chapter_id: string, model: string, 
/**
 * Project POV string (e.g. "third-limited") used by the
 * deterministic POV-drift detector.  Empty / null skips POV checks.
 */
project_pov: string | null, high_confidence_mode: boolean | null, };
