// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ContinuityScenePassDto } from "./ContinuityScenePassDto";

/**
 * Result of `agent_run_developmental_review`.
 */
export type RunDevelopmentalReviewResult = { chapter_id: string, dev_run_id: string, dev_task_id: string, dev_status: string, 
/**
 * JSON-serialised `DevelopmentalNotes` on success, null otherwise.
 */
dev_notes_json: string | null, dev_error: string | null, dev_raw: string | null, continuity_passes: Array<ContinuityScenePassDto>, scenes_scanned: number, };
