// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type RunHumanizationInput = { project_id: string, node_id: string, model: string, high_confidence_mode: boolean | null, };
