// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Result of the chained run.  Both halves surface — the UI can show
 * the brief above the outline and let the user re-run if the brief
 * looks off.  All fields are best-effort: `brief = None` when the
 * intake call failed; `outline = None` when the brief was rejected
 * or the outline call failed.
 */
export type RunIntakeAndOutlineResult = { intake_run_id: string, intake_task_id: string, 
/**
 * JSON of `ProjectBrief` on intake success, null otherwise.
 */
brief_json: string | null, intake_error: string | null, intake_raw: string | null, outline_run_id: string | null, outline_task_id: string | null, 
/**
 * "completed" | "invalid" | "error" | "cancelled" | "skipped"
 */
outline_status: string, 
/**
 * JSON of `OutlineProposal` on outline success.
 */
outline_json: string | null, outline_error: string | null, outline_raw: string | null, };
