// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type RunIntakeInput = { project_id: string, idea_text: string, preferred_mode: string | null, model: string, };
