// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Input to the `agent_run_outline` Tauri command.
 */
export type RunOutlineInput = { 
/**
 * ULID of the open project.
 */
project_id: string, 
/**
 * JSON-serialised `ProjectBrief` (validated client-side before sending).
 */
brief_json: string, 
/**
 * Desired chapter count (6–60).
 */
target_chapter_count: number, 
/**
 * Optional genre overlay string.
 */
genre_overlay: string | null, 
/**
 * Ollama model tag to use (e.g. `"qwen3.5:9b"`). Optional — when
 * `None` or empty, the backend resolves the right tier (Light for
 * outline-architect) from the installed models. The UI no longer
 * asks the user to pick a model; this field exists only for the
 * CLI examples and tests that want to force a specific tag.
 */
model: string | null, };
