// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Input to the `agent_run_outline` Tauri command.
 */
export type RunOutlineInput = { 
/**
 * ULID of the open project.
 */
project_id: string, 
/**
 * JSON-serialised `ProjectBrief` (validated client-side before sending).
 */
brief_json: string, 
/**
 * Desired chapter count (6–60).
 */
target_chapter_count: number, 
/**
 * Optional genre overlay string.
 */
genre_overlay: string | null, 
/**
 * Ollama model tag to use (e.g. "qwen2.5:7b-instruct-q4_K_M").
 */
model: string, };
