// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Input to `agent_run_polish_stage`. The `stage` field selects which
 * of the four specialist polishers to invoke
 * (`"dialogue" | "metaphor" | "voice" | "scene_tension"`).
 */
export type RunPolishStageInput = { project_id: string, scene_id: string, stage: string, 
/**
 * Genre context that the per-stage prompt branches on
 * (`"literary_fiction" | "genre_fiction" | "non_fiction"`).
 */
genre_label: string, 
/**
 * Optional voice constraints block (filled from `booksforge-voice`
 * in Phase 3; empty string is acceptable for Phase 2).
 */
voice_constraints: string, 
/**
 * POV character name. Drives metaphor-polish's character-specific
 * imagery rule. Empty string acceptable.
 */
pov_character: string, model: string, };
