// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Input to `agent_run_scene_drafter_fic`.
 */
export type RunSceneDrafterFicInput = { project_id: string, node_id: string, scene_goal: string, scene_conflict: string, scene_reveal: string, target_words: number, chapter_pov: string, 
/**
 * `"literary_fiction"` | `"genre_fiction"`. Drives the prompt's
 * genre-lens block.
 */
genre_lens: string, model: string, };
