// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type RunVocabDictionaryInput = { project_id: string, model: string, 
/**
 * How many recent edit decisions to feed in.  Default 30.
 */
lookback: number | null, };
