// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Input to `agent_run_world_bible`.
 */
export type RunWorldBibleInput = { project_id: string, model: string, };
