// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Result of `save_diagnostic_bundle`.
 */
export type SaveDiagnosticBundleResult = { output_path: string, bytes: bigint, log_files_included: number, redaction_applied: boolean, };
