// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs).
// Do not edit this file manually.

export type SmokeTestResult = {
  success: boolean;
  /** A short excerpt of the model's response (for the UI to display). */
  response: string | null;
  duration_ms: number;
  /** Error message if the test failed. */
  error: string | null;
};
