// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Input to `snapshot_list`.  An empty struct lists all snapshots.
 */
export type SnapshotListInput = { scope_id: string | null, };
