// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Input to `snapshot_restore`.
 */
export type SnapshotRestoreInput = { snapshot_id: string, 
/**
 * If `Some`, only these node ULIDs are restored.  Omit for whole-tree.
 */
selective: Array<string> | null, };
