// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One axis of validation report shaped for the frontend.
 */
export type ValidationCheckDto = { 
/**
 * "schema" | "redaction" | "length" | "entity_sanity" | "memory_scope" |
 * "idempotent" | "range" | "contract" |
 * "faithfulness" | "style" | "coherence" | "self_consistency"
 */
axis: string, 
/**
 * "pass" | "warn" | "fail"
 */
outcome: string, evidence: string, remediation: string | null, };
