// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ValidatorIssueDto } from "./ValidatorIssueDto";

/**
 * The whole-batch report returned by `validators_run`.
 */
export type ValidatorReportDto = { run_id: string, 
/**
 * "ok" | "warnings" | "errors" | "crashed".
 */
status: string, duration_ms: bigint, error_count: number, warning_count: number, info_count: number, issues: Array<ValidatorIssueDto>, };
