// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type VocabListInput = { 
/**
 * Layer slugs to fetch.  Empty = no rows returned.  Common defaults:
 * `["project", "ai_tells"]`.
 */
layers: Array<string>, };
