// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Input to the `vocab_apply_proposals` Tauri command (BACKLOG §E0d.10).
 * Accepts the indices the user picked from the vocab-dictionary's
 * `VocabUpdateProposals` and writes them to the project layer.  Index
 * arrays default to "all" when omitted at the call site (the UI passes
 * explicit lists once the user has reviewed each row).
 */
export type VocabApplyInput = { 
/**
 * `agent_tasks.id` of the vocab-dictionary run that produced the
 * proposals.  The orchestrator looks up the persisted proposal
 * via this id (same pattern as `agent_apply_copyedit`).
 */
task_id: string, 
/**
 * Indices into `VocabUpdateProposals.additions` that the user
 * accepted.  Empty array = none accepted.
 */
accepted_addition_indices: Array<number>, 
/**
 * Indices into `VocabUpdateProposals.modifications` that the user
 * accepted.  Empty array = none accepted.
 */
accepted_modification_indices: Array<number>, };
