// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Numeric voice profile.
 */
export type VoiceProfile = { word_count: number, sentence_count: number, paragraph_count: number, median_sentence_length: number, p25_sentence_length: number, p75_sentence_length: number, 
/**
 * Share (0-1) of sentences shorter than 8 words.
 */
pct_short_sentences: number, 
/**
 * Share (0-1) of sentences longer than 25 words.
 */
pct_long_sentences: number, 
/**
 * Share (0-1) of sentences containing dialogue marks.
 */
dialogue_ratio: number, avg_paragraph_length_sentences: number, 
/**
 * Type-token ratio (vocab richness, 0-1).
 */
type_token_ratio: number, 
/**
 * Share of words NOT in the COMMON_WORDS list (0-1).
 */
rare_word_ratio: number, em_dash_per_1000: number, semicolon_per_1000: number, parenthetical_per_1000: number, avg_word_length: number, 
/**
 * Share of words with one syllable (rough cadence proxy).
 */
pct_monosyllabic_words: number, 
/**
 * Moving-Average Type-Token Ratio with a 50-token sliding window.
 * Reports 0.0 if the prose has fewer than 50 tokens (window doesn't
 * fit). Use this — not [`Self::type_token_ratio`] — for any
 * cross-run comparison where word counts differ.
 */
mattr_50: number, 
/**
 * Measure of Textual Lexical Diversity. Bidirectional walk through
 * tokens; each time the running TTR drops below the 0.72 threshold
 * constitutes a "factor". `total_tokens / factors` (averaged
 * forward + backward). Reports 0.0 for prose under ~50 tokens.
 */
mtld: number, };
